version: '3.8'

services:
  postegres_nlw:
    container_name: postegres_nlw
    image: postgres 
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pg_nlw